---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: po1-b2c-cms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: po1-b2c-cms
  template:
    metadata:
      labels:
        app: po1-b2c-cms
    spec:
      serviceAccountName: po1-b2c-cms
      containers:
      - name: po1-b2c-cms
        imagePullPolicy: Always
        image: 236731556556.dkr.ecr.eu-west-1.amazonaws.com/po1/po1-b2c-cms:latest

        ports:
        - name: http
          containerPort: 8080

        envFrom:
        - configMapRef:
            name: po1-b2c-cms

        env:
        - name: ConnectionStrings__umbracoDbDSN
          valueFrom:
            secretKeyRef:
              name: po1-b2c-cms
              key: umbracoDbDSN

        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.1"
            memory: "100Mi"
        volumeMounts:
        - name: po1-b2c-cms-media
          mountPath: /app/wwwroot/media/

      volumes:
        - name: po1-b2c-cms-media
          persistentVolumeClaim:
            claimName: po1-b2c-cms-efs