---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: po1-b2c-cms
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: po1-b2c-cms
  conditions:
    - namespaces:
        # Namespace allowed to acces this secret store
        - po1
