---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: po1-b2c-cms
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:236731556556:certificate/625584ae-88bf-435c-b881-8e5f34dee82c
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/group.name: po1
    alb.ingress.kubernetes.io/group.order: '4'
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - host: po1-b2c-cms.dev.travcorpservices.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: po1-b2c-cms
                port:
                  name: http
  tls:
  - hosts:
    - po1-b2c-cms.dev.travcorpservices.com