apiVersion: v1
kind: Secret
metadata:
  name: po1-bc2-cms
stringData:
  umbracoDbDSN: WillBeFilledOutByExternalSecrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecret-argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
  target:
    # The name of the K8 secret to put the secret in (match above secret)
    name: po1-bc2-cms
    creationPolicy: Merge
  data:
  - secretKey: umbracoDbDSN # local field (in the above secret stringData)
    remoteRef:
      key: po1-k8-bc2-cms # AWS Secrets Manager secret name
      property: umbracoDbDSN # AWS Secrets Manager secret key