apiVersion: v1
kind: Secret
metadata:
  name: po1-b2c-cms
stringData:
  umbracoDbDSN: WillBeFilledOutByExternalSecrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: po1-b2c-cms
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: po1-b2c-cms
  target:
    # The name of the K8 secret to put the secret in (match above secret)
    name: po1-b2c-cms
    creationPolicy: Merge
  data:
  - remoteRef:
      key: po1-k8-b2c-cms # AWS Secrets Manager secret name
      property: umbracoDbDSN # AWS Secrets Manager secret key
    secretKey: umbracoDbDSN # local field (in the above secret stringData)
