---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: po1-b2c-cms
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0c0c55ced34d4cbc7
  directoryPerms: "700"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: po1-b2c-cms-efs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi